# Railway configuration
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -m app.main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "set-game-api"
internal_port = 8000
healthcheck = { path = "/api/health", interval = "10s", timeout = "5s", retries = 5 }

# Resource specifications
[services.resources]
cpu = "1x"
memory = "1GB"
